default: check dry

fmt:
    @echo "TODO fmt"

check:
    ansible-lint

dry:
    ansible-playbook main.yaml --check

deploy tags="all":
    ansible-playbook main.yaml --tags {{tags}}

reset:
    ansible-playbook reset/reset.yaml
